import type { Metadata } from "next";
import { company } from "@/content/company";
import { getPage } from "@/content/pages";
import type { Article, Locale, PageKey } from "@/content/types";
import { path, routes } from "./routes";

const url = (p: string) => `${company.domain}${p === "/" ? "" : p}`;
const ORG_ID = `${company.domain}/#organization`;

/** Metadata shared by every page of a locale (set in the root layout). */
export function baseMetadata(locale: Locale): Metadata {
  return {
    metadataBase: new URL(company.domain),
    applicationName: company.name,
    authors: [{ name: company.name, url: company.domain }],
    creator: company.name,
    publisher: company.name,
    category: locale === "ar" ? "طاقة شمسية" : "Énergie solaire",
    robots: {
      index: true,
      follow: true,
      googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1, "max-video-preview": -1 },
    },
    icons: { icon: [{ url: "/icon.svg", type: "image/svg+xml" }], apple: "/apple-touch-icon.png" },
    manifest: "/manifest.webmanifest",
    formatDetection: { telephone: false, email: false, address: false },
    verification: process.env.NEXT_PUBLIC_GSC_VERIFICATION
      ? { google: process.env.NEXT_PUBLIC_GSC_VERIFICATION }
      : undefined,
    openGraph: { siteName: company.name, locale: locale === "ar" ? "ar_TN" : "fr_TN" },
  };
}

/** Title, description, canonical, hreflang, Open Graph and Twitter for one URL. */
export function pageMetadata(
  locale: Locale,
  { title, description, frPath, arPath, type = "website", imageAlt, publishedTime, section }: {
    title: string;
    description: string;
    frPath: string;
    arPath: string;
    type?: "website" | "article";
    imageAlt?: string;
    publishedTime?: string;
    section?: string;
  }
): Metadata {
  const self = locale === "ar" ? arPath : frPath;
  // Per-page 1200×630 PNG generated by app/og/[locale]/[[...slug]]/route.tsx.
  // arPath is the un-prefixed slug (Arabic is served at the root).
  const image = {
    url: `/og/${locale}${arPath === "/" ? "" : arPath}`,
    width: 1200,
    height: 630,
    type: "image/png",
    alt: imageAlt ?? title,
  };
  return {
    title: { absolute: title },
    description,
    alternates: {
      canonical: self,
      languages: { ar: arPath, fr: frPath, "x-default": arPath },
    },
    openGraph: {
      type,
      url: self,
      siteName: company.name,
      title,
      description,
      locale: locale === "ar" ? "ar_TN" : "fr_TN",
      alternateLocale: locale === "ar" ? ["fr_TN"] : ["ar_TN"],
      images: [image],
      ...(type === "article" ? { publishedTime, modifiedTime: publishedTime, section, authors: [company.name] } : {}),
    },
    twitter: { card: "summary_large_image", title, description, images: [image] },
  };
}

export function metadataFor(locale: Locale, key: PageKey): Metadata {
  const { seo, hero } = getPage(locale, key);
  return pageMetadata(locale, { ...seo, imageAlt: hero.h1, frPath: path("fr", key), arPath: path("ar", key) });
}

export function articleMetadata(locale: Locale, a: Article): Metadata {
  const suffix = `actualites/${a.slug}`;
  return pageMetadata(locale, {
    title: `${a.title} | ${company.name}`,
    description: a.excerpt,
    frPath: `/fr/${suffix}`,
    arPath: `/${suffix}`,
    type: "article",
    imageAlt: a.title,
    publishedTime: a.date,
    section: a.category,
  });
}

/* ---------------- Schema.org (JSON-LD) ---------------- */

function organization(locale: Locale) {
  return {
    "@type": ["Organization", "LocalBusiness"],
    "@id": ORG_ID,
    name: company.name,
    slogan: company.signature,
    url: company.domain,
    logo: url("/logo-mark.svg"),
    image: url("/og/ar"),
    email: company.emails[0],
    telephone: company.phones.map((p) => p.tel),
    address: {
      "@type": "PostalAddress",
      streetAddress: company.address.street,
      addressLocality: company.address.city,
      addressCountry: company.address.country,
    },
    areaServed: { "@type": "Country", name: "Tunisia" },
    contactPoint: company.phones.map((p) => ({
      "@type": "ContactPoint",
      telephone: p.tel,
      contactType: "customer service",
      availableLanguage: ["fr", "ar"],
    })),
    sameAs: Object.values(company.social),
    inLanguage: locale,
  };
}

const SERVICE_KEYS: PageKey[] = ["pv", "pumping", "storage", "mobility", "engineering", "metaform"];

export function breadcrumbLd(items: { name: string; path: string }[]) {
  return {
    "@type": "BreadcrumbList",
    itemListElement: items.map((it, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: it.name,
      item: url(it.path),
    })),
  };
}

export function jsonLd(locale: Locale, key: PageKey, crumbs: { name: string; path: string }[]) {
  const page = getPage(locale, key);
  const graph: object[] = [
    organization(locale),
    {
      "@type": "WebSite",
      "@id": `${company.domain}/#website`,
      url: company.domain,
      name: company.name,
      inLanguage: ["fr", "ar"],
      publisher: { "@id": ORG_ID },
    },
    {
      "@type": "WebPage",
      url: url(path(locale, key)),
      name: page.seo.title,
      description: page.seo.description,
      inLanguage: locale,
      isPartOf: { "@id": `${company.domain}/#website` },
    },
  ];
  if (crumbs.length > 1) graph.push(breadcrumbLd(crumbs));

  if (key === "home" || key === "solutions") {
    for (const k of SERVICE_KEYS) {
      const p = getPage(locale, k);
      graph.push({
        "@type": "Service",
        name: p.hero.h1,
        description: p.seo.description,
        url: url(path(locale, k)),
        provider: { "@id": ORG_ID },
        areaServed: "TN",
      });
    }
  } else if (SERVICE_KEYS.includes(key)) {
    graph.push({
      "@type": "Service",
      name: page.hero.h1,
      description: page.seo.description,
      url: url(path(locale, key)),
      provider: { "@id": ORG_ID },
      areaServed: "TN",
    });
  }

  for (const b of page.blocks) {
    if (b.type === "faq") {
      graph.push({
        "@type": "FAQPage",
        mainEntity: b.items.map((q) => ({
          "@type": "Question",
          name: q.q,
          acceptedAnswer: { "@type": "Answer", text: q.a },
        })),
      });
    }
  }
  return { "@context": "https://schema.org", "@graph": graph };
}

export function articleLd(locale: Locale, a: Article, crumbs: { name: string; path: string }[]) {
  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Article",
        headline: a.title,
        description: a.excerpt,
        datePublished: a.date,
        dateModified: a.date,
        inLanguage: locale,
        articleSection: a.category,
        url: url(path(locale, "news", a.slug)),
        image: url(`/og/${locale}/${routes.news}/${a.slug}`),
        author: { "@id": ORG_ID },
        publisher: { "@id": ORG_ID },
      },
      organization(locale),
      breadcrumbLd(crumbs),
    ],
  };
}

export function JsonLd({ data }: { data: object }) {
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data).replace(/</g, "\\u003c") }}
    />
  );
}

