import type { Locale, PageKey } from "./types";

type NavEntry = { key: PageKey; label: string } | { label: string; children: { key: PageKey; label: string }[] };

const fr = {
  dir: "ltr" as "ltr" | "rtl",
  lang: "fr",
  signature: "Engineering Energy. Building the Future.",
  nav: [
    {
      label: "Solutions",
      children: [
        { key: "solutions", label: "Toutes nos solutions" },
        { key: "pv", label: "Photovoltaïque" },
        { key: "pumping", label: "Pompage solaire" },
        { key: "storage", label: "Stockage" },
        { key: "mobility", label: "Mobilité électrique" },
        { key: "engineering", label: "Ingénierie & bureau d’études" },
        { key: "metaform", label: "METAFORM" },
      ],
    },
    { key: "projects", label: "Réalisations" },
    {
      label: "Ressources",
      children: [
        { key: "expertise", label: "Expertise" },
        { key: "news", label: "Actualités" },
        { key: "faq", label: "FAQ" },
      ],
    },
    { key: "contact", label: "Contact" },
  ] as NavEntry[],
  cta: {
    study: "Demander une étude",
    expert: "Parler à un expert",
    email: "Envoyer un e-mail",
    call: "Appeler",
    whatsapp: "WhatsApp",
    more: "En savoir plus",
    readMore: "Lire l’article",
    allNews: "Toutes les actualités",
    allProjects: "Toutes les réalisations",
    back: "Retour",
  },
  flow: {
    title: "De l’énergie solaire à votre consommation.",
    sub: "Chaque installation est une chaîne complète, pensée de la captation à la consommation.",
    steps: [
      { key: "sun", title: "Soleil", desc: "La ressource : une irradiation élevée, à exploiter au mieux selon l’orientation et l’inclinaison." },
      { key: "panels", title: "Panneaux photovoltaïques", desc: "Les modules convertissent le rayonnement solaire en courant continu." },
      { key: "inverter", title: "Onduleur", desc: "Le courant continu est converti en courant alternatif utilisable." },
      { key: "smart", title: "Gestion intelligente", desc: "Le système pilote la production, la consommation et les priorités." },
      { key: "home", title: "Consommation", desc: "Le bâtiment consomme d’abord sa propre énergie solaire." },
      { key: "battery", title: "Stockage", desc: "Le surplus peut être stocké selon l’architecture retenue." },
    ],
  },
  home: "Accueil",
  companyPage: "VERTUS Technology",
  breadcrumb: "Fil d’Ariane",
  ceo: {
    title: "Mot du CEO",
    body: [
      "Chez VERTUS Technology, nous abordons chaque projet énergétique comme une problématique technique et économique à résoudre, pas comme une simple vente d’équipements.",
      "Notre objectif est de comprendre le besoin réel de chaque client, de concevoir une solution cohérente et optimisée, puis de l’accompagner de l’étude jusqu’à la mise en service, et au-delà.",
    ],
    quote: "Nous ne vendons pas uniquement des équipements. Nous concevons des solutions.",
    signature: "CEO — VERTUS Technology",
  },
  projects: {
    filters: [
      { key: "all", label: "Tous" },
      { key: "residentiel", label: "Résidentiel" },
      { key: "industriel", label: "Industriel" },
      { key: "agricole", label: "Agricole" },
      { key: "commercial", label: "Commercial" },
    ],
    labels: {
      sector: "Client / secteur",
      location: "Localisation",
      type: "Type",
      power: "Puissance",
      problem: "Problématique",
      solution: "Solution",
      result: "Résultat",
    },
  },
  contact: {
    phone: "Téléphone / WhatsApp",
    email: "E-mail",
    address: "Siège social",
    hours: "Horaires",
    map: "Carte : Centre Urbain Nord, Ariana",
    loadMap: "Afficher la carte",
    mapNotice: "La carte est fournie par Google Maps et n’est chargée qu’à votre demande.",
    whatsappText: "Bonjour VERTUS Technology, je souhaite parler à un expert au sujet de mon projet.",
  },
  form: {
    title: "Demander une étude",
    lead: "Décrivez votre projet : notre bureau d’études l’analyse et revient vers vous avec une première orientation technique.",
    sections: { you: "Vos coordonnées", project: "Votre projet", details: "Informations techniques (facultatif)", message: "Votre message" },
    fields: {
      fullName: "Nom et prénom",
      company: "Entreprise",
      phone: "Téléphone",
      email: "E-mail",
      city: "Ville",
      projectType: "Type de projet",
      power: "Puissance souhaitée (kWc)",
      consumption: "Consommation annuelle (kWh)",
      bill: "Facture moyenne (TND / mois)",
      surface: "Surface disponible (m²)",
      roof: "Type de toiture",
      storage: "Stockage",
      pumping: "Pompage",
      ev: "Recharge VE",
      message: "Message",
      files: "Pièces jointes",
    },
    removeFile: "Retirer",
    filesHint: "PDF, JPG ou PNG — 3 fichiers maximum, 5 Mo chacun (factures, plans, photos du site…).",
    projectTypes: [
      "Photovoltaïque résidentiel",
      "Photovoltaïque professionnel / commercial",
      "Photovoltaïque industriel",
      "Photovoltaïque agricole",
      "Pompage solaire",
      "Stockage d’énergie",
      "Mobilité électrique",
      "Ingénierie / bureau d’études",
      "METAFORM — solutions métalliques",
      "Autre",
    ],
    roofTypes: ["Dalle / toit plat", "Toiture inclinée", "Bac acier", "Au sol", "Autre / je ne sais pas"],
    yes: "Oui",
    no: "Non",
    choose: "Choisir…",
    optional: "facultatif",
    required: "obligatoire",
    consent: "J’accepte que mes données soient utilisées pour traiter ma demande, conformément à la politique de confidentialité.",
    submit: "Envoyer ma demande",
    sending: "Envoi en cours…",
    success: "Merci, votre demande a bien été reçue. Notre équipe vous contactera prochainement.",
    error: "L’envoi n’a pas abouti. Vérifiez votre connexion et réessayez, ou contactez-nous par téléphone ou WhatsApp.",
    tooFast: "Envoi trop rapide détecté. Merci de patienter quelques secondes et de réessayer.",
    validation: {
      required: "Ce champ est obligatoire",
      email: "Adresse e-mail invalide",
      phone: "Numéro de téléphone invalide",
      number: "Veuillez saisir un nombre",
      fileType: "Formats acceptés : PDF, JPG, PNG",
      fileSize: "Chaque fichier doit faire moins de 5 Mo",
      fileCount: "3 fichiers maximum",
      consent: "Veuillez accepter pour envoyer votre demande",
    },
  },
  cookies: {
    text: "Nous utilisons des cookies de mesure d’audience pour améliorer le site. Ils ne sont déposés qu’avec votre accord.",
    accept: "Accepter",
    decline: "Refuser",
    more: "En savoir plus",
  },
  notFound: {
    title: "Page introuvable",
    text: "La page demandée n’existe pas ou a été déplacée.",
    home: "Retour à l’accueil",
  },
  footer: {
    navTitle: "Navigation",
    solutionsTitle: "Solutions",
    contactTitle: "Contact",
    legal: "Mentions légales",
    privacy: "Politique de confidentialité",
    cookies: "Gérer les cookies",
    copyright: "© 2026 VERTUS Technology. Tous droits réservés.",
  },
  a11y: {
    skip: "Aller au contenu",
    switchLang: "التبديل إلى العربية",
    openMenu: "Ouvrir le menu",
    closeMenu: "Fermer le menu",
    prev: "Précédent",
    next: "Suivant",
    themeToLight: "Passer en mode clair",
    themeToDark: "Passer en mode sombre",
    whatsapp: "Écrire sur WhatsApp",
    call: "Appeler VERTUS Technology",
    submenu: "Ouvrir le sous-menu",
  },
};

export type Ui = typeof fr;

const ar: Ui = {
  dir: "rtl",
  lang: "ar",
  signature: "Engineering Energy. Building the Future.",
  nav: [
    {
      label: "الحلول",
      children: [
        { key: "solutions", label: "كل حلولنا" },
        { key: "pv", label: "الطاقة الكهروضوئية" },
        { key: "pumping", label: "الضخ الشمسي" },
        { key: "storage", label: "التخزين" },
        { key: "mobility", label: "التنقل الكهربائي" },
        { key: "engineering", label: "الهندسة ومكتب الدراسات" },
        { key: "metaform", label: "METAFORM" },
      ],
    },
    { key: "projects", label: "الإنجازات" },
    {
      label: "موارد",
      children: [
        { key: "expertise", label: "الخبرة" },
        { key: "news", label: "الأخبار" },
        { key: "faq", label: "الأسئلة الشائعة" },
      ],
    },
    { key: "contact", label: "اتصل بنا" },
  ],
  cta: {
    study: "اطلب دراسة",
    expert: "تحدث إلى خبير",
    email: "أرسل بريداً إلكترونياً",
    call: "اتصل",
    whatsapp: "واتساب",
    more: "اعرف المزيد",
    readMore: "اقرأ المقال",
    allNews: "كل الأخبار",
    allProjects: "كل الإنجازات",
    back: "رجوع",
  },
  flow: {
    title: "من الطاقة الشمسية إلى استهلاكك.",
    sub: "كل منظومة سلسلة متكاملة، مصمَّمة من الالتقاط إلى الاستهلاك.",
    steps: [
      { key: "sun", title: "الشمس", desc: "المورد: إشعاع مرتفع يُستغل على أفضل وجه حسب الاتجاه والميل." },
      { key: "panels", title: "الألواح الكهروضوئية", desc: "تحوّل الوحدات الإشعاع الشمسي إلى تيار مستمر." },
      { key: "inverter", title: "العاكس", desc: "يُحوَّل التيار المستمر إلى تيار متناوب قابل للاستعمال." },
      { key: "smart", title: "الإدارة الذكية", desc: "يتحكم النظام في الإنتاج والاستهلاك والأولويات." },
      { key: "home", title: "الاستهلاك", desc: "يستهلك المبنى أولاً طاقته الشمسية الخاصة." },
      { key: "battery", title: "التخزين", desc: "يمكن تخزين الفائض حسب البنية المعتمدة." },
    ],
  },
  home: "الرئيسية",
  companyPage: "فيرتوس تكنولوجي",
  breadcrumb: "مسار التصفح",
  ceo: {
    title: "كلمة المدير العام",
    body: [
      "في فيرتوس تكنولوجي، نتعامل مع كل مشروع طاقي كإشكالية تقنية واقتصادية يجب حلّها، لا كمجرد بيع للمعدات.",
      "هدفنا فهم الحاجة الحقيقية لكل حريف، وتصميم حل متناسق ومُحسَّن، ثم مرافقته من الدراسة إلى التشغيل وما بعده.",
    ],
    quote: "لا نبيع المعدات فحسب، بل نصمّم الحلول.",
    signature: "المدير العام — فيرتوس تكنولوجي",
  },
  projects: {
    filters: [
      { key: "all", label: "الكل" },
      { key: "residentiel", label: "سكني" },
      { key: "industriel", label: "صناعي" },
      { key: "agricole", label: "فلاحي" },
      { key: "commercial", label: "تجاري" },
    ],
    labels: {
      sector: "الحريف / القطاع",
      location: "الموقع",
      type: "النوع",
      power: "القدرة",
      problem: "الإشكالية",
      solution: "الحل",
      result: "النتيجة",
    },
  },
  contact: {
    phone: "الهاتف / واتساب",
    email: "البريد الإلكتروني",
    address: "المقر الاجتماعي",
    hours: "أوقات العمل",
    map: "الخريطة: المركز العمراني الشمالي، أريانة",
    loadMap: "عرض الخريطة",
    mapNotice: "الخريطة مقدّمة من خرائط Google ولا يتم تحميلها إلا بطلب منك.",
    whatsappText: "مرحباً فيرتوس تكنولوجي، أرغب في التحدث إلى خبير بخصوص مشروعي.",
  },
  form: {
    title: "اطلب دراسة",
    lead: "صف لنا مشروعك: يحلّله مكتب الدراسات لدينا ويعود إليك بتوجيه تقني أولي.",
    sections: { you: "بياناتك", project: "مشروعك", details: "معلومات تقنية (اختيارية)", message: "رسالتك" },
    fields: {
      fullName: "الاسم واللقب",
      company: "الشركة",
      phone: "الهاتف",
      email: "البريد الإلكتروني",
      city: "المدينة",
      projectType: "نوع المشروع",
      power: "القدرة المطلوبة (كيلوواط ذروة)",
      consumption: "الاستهلاك السنوي (كيلوواط ساعة)",
      bill: "معدّل الفاتورة (دينار / شهر)",
      surface: "المساحة المتاحة (م²)",
      roof: "نوع السطح",
      storage: "التخزين",
      pumping: "الضخ",
      ev: "شحن السيارات الكهربائية",
      message: "الرسالة",
      files: "المرفقات",
    },
    removeFile: "إزالة",
    filesHint: "PDF أو JPG أو PNG — 3 ملفات كحد أقصى، 5 ميغابايت لكل ملف (فواتير، مخططات، صور الموقع…).",
    projectTypes: [
      "كهروضوئي سكني",
      "كهروضوئي مهني / تجاري",
      "كهروضوئي صناعي",
      "كهروضوئي فلاحي",
      "ضخ شمسي",
      "تخزين الطاقة",
      "التنقل الكهربائي",
      "هندسة / مكتب دراسات",
      "METAFORM — حلول معدنية",
      "آخر",
    ],
    roofTypes: ["سطح مستوٍ", "سطح مائل", "صفائح فولاذية", "على الأرض", "آخر / لا أعرف"],
    yes: "نعم",
    no: "لا",
    choose: "اختر…",
    optional: "اختياري",
    required: "إجباري",
    consent: "أوافق على استعمال بياناتي لمعالجة طلبي، وفقاً لسياسة الخصوصية.",
    submit: "أرسل طلبي",
    sending: "جارٍ الإرسال…",
    success: "شكراً، تم استلام طلبك. سيتصل بك فريقنا قريباً.",
    error: "لم يتم الإرسال. تحقق من اتصالك وأعد المحاولة، أو اتصل بنا عبر الهاتف أو واتساب.",
    tooFast: "تم رصد إرسال سريع جداً. يرجى الانتظار بضع ثوانٍ وإعادة المحاولة.",
    validation: {
      required: "هذا الحقل إجباري",
      email: "البريد الإلكتروني غير صالح",
      phone: "رقم الهاتف غير صالح",
      number: "يرجى إدخال رقم",
      fileType: "الصيغ المقبولة: PDF و JPG و PNG",
      fileSize: "يجب أن يكون حجم كل ملف أقل من 5 ميغابايت",
      fileCount: "3 ملفات كحد أقصى",
      consent: "يرجى الموافقة لإرسال طلبك",
    },
  },
  cookies: {
    text: "نستعمل ملفات تعريف الارتباط لقياس الزيارات وتحسين الموقع. لا يتم وضعها إلا بموافقتك.",
    accept: "قبول",
    decline: "رفض",
    more: "اعرف المزيد",
  },
  notFound: {
    title: "الصفحة غير موجودة",
    text: "الصفحة المطلوبة غير موجودة أو تم نقلها.",
    home: "العودة إلى الرئيسية",
  },
  footer: {
    navTitle: "روابط",
    solutionsTitle: "الحلول",
    contactTitle: "اتصل بنا",
    legal: "البيانات القانونية",
    privacy: "سياسة الخصوصية",
    cookies: "إدارة ملفات تعريف الارتباط",
    copyright: "© 2026 فيرتوس تكنولوجي. جميع الحقوق محفوظة.",
  },
  a11y: {
    skip: "انتقل إلى المحتوى",
    switchLang: "Passer au français",
    openMenu: "افتح القائمة",
    closeMenu: "أغلق القائمة",
    prev: "السابق",
    next: "التالي",
    themeToLight: "التبديل إلى الوضع الفاتح",
    themeToDark: "التبديل إلى الوضع الداكن",
    whatsapp: "راسلنا عبر واتساب",
    call: "اتصل بفيرتوس تكنولوجي",
    submenu: "افتح القائمة الفرعية",
  },
};

export function getUi(locale: Locale): Ui {
  return locale === "ar" ? ar : fr;
}

export type { NavEntry };
